### ISSUE TITLE
Randomly pause during epoch, neither output nor error

### ISSUE THREAD

**Issue by lucysun756** [mwdhont/SimCLRv1-keras-tensorflow#6]
Hello, @mwdhont.
what platform did you experiment on？windows or linux?
I have random pauses during training, especially during iterations. The process hangs, the program neither outputs nor reports errors, the situation will be improved by increasing the batch size, but it still exists.Often get stuck in the middle of an epoch, unable to proceed to the next steps.
Thanks.

**Comment by mwdhont** [comment]
Hi @lucysun756,

Most of the experiments were run in a docker container, using Linux. On Google Colab everything works fine as well. Could it be that your hardware is insufficient? 

Michiel
